language: node_js

node_js: stable

cache: yarn

before_install: yarn global add greenkeeper-lockfile

before_script: greenkeeper-lockfile-update

script: yarn lint

after_script: greenkeeper-lockfile-upload

deploy:
  provider: npm
  email: liujiaren1992@vip.qq.com
  api_key:
    secure: i0h2Qk7fT2pChSCoWygSXr1EUtqyxTPyW8eQ9hH3d6FjhuS0aFXCTbcuKdbQReNx0a6yLyrX1iD1nhmj9z8ael/4JWVee19g2g7RHnHJEjFZEXNSfV2WX58De82BoeXKTP8HiyDr83zBbrdqazmYd/TpW4bc9OX7r1RlVW6IJhBJLQuebmKxYSOwZrfS9g9sUu+WrVM+nzrbkIwhjxIvoinpuByT6V1GQErXvtotO3W/VlW5J7ICSho1iNrRiqCTCVNszfIUKWCadB7VUU4bulWbQpnnSvxLuT5DunMUDpM9L83UAGC+G8BV0AmjeG6h+vvRlaOfrArrCgAbsiZGrVmxBTbTQdX7YH9YL836p1HR+1xs/KbDu1PGBOpO6AxM/vYzfAQJw2WfJD7VhyvWCMpPVf/gckCBvY/Hbtj0q8+JmY+azWAJ9bMxKy0MAnp+FTq4tkBQrj8xM4w7FBfr5C1uopw83pIXM91FQwx4s0IyzgQk5FWe48jLl4b8OfkaRqObcVjSrZqZXsXWhooSfXiUtCyOMQzncqJJ5n2BUak+YS+SqSTvHb/AGs0NT+l/Z36LlIZ0MpNLGRvubHUnT9xnd6ySakqtirOwOZWsGSrtF7FvGNWWkuV2WxdNFIkCoPrg6zT1ZBANSr8d6GSn8vGmg+zqDZY3HJqUqTdHWPc=
  on:
    tag: true
